schema_version = "1.0.0"
id = "actionrecorder"
name = "ActionRecorder"
version = "4.1.2"
tagline = "Record and replay Blender actions"
maintainer = "RivinHD"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/InamuraJIN/ActionRecorder"
